### ISSUE TITLE
imp_raven

### ISSUE THREAD

**Issue by Styndel** [maRce10/Rraven#1]
When running the example code (copy/paste) listed on [https://marce10.github.io/2017/11/30/Rraven-_Connecting_R_and_Raven_Sound_Analysis_Software.html](url) the following error occurs:

`rvn.dat` <- imp_raven(all.data = `TRUE)
`
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

`rvn.dat <- imp_raven(all.data = TRUE, waveform = TRUE)
`
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

`rvn.dat <- imp_raven(sound.file.col = "End.File", all.data = FALSE, freq.cols = TRUE)
`
Error in FUN(X[[i]], ...) : 
  'End.File' column provided in 'sound.file.col' not found (make sure no other '.txt' files are found in that directory

With my own data (which for simplicity at this moment is one folder with 1 wave file of a track and 1 selection table) `rvn.dat <- imp_raven(all.data = TRUE)` works succesfully. 

However, `rvn.dat <- imp_raven(sound.file.col = "End.File", all.data=FALSE, freq.cols = TRUE)` returns the same error as with the example code:

Error in FUN(X[[i]], ...) : 
  'End.File' column provided in 'sound.file.col' not found (make sure no other '.txt' files are found in that directory

It seems to be something with all.data = FALSE. If I also set all.data to TRUE it works in every case (except for with the example code which does not work and gives the error in Rbind output). 

I would appreciate any insight into this error and to know if it's perhaps something I am doing wrong, or something wrong with the imp_raven function. Thank you very much.

**Comment by maRce10** [comment]
Hi Styndel,

sorry for the late response. I think that bug was fix in the latest Rraven version. Please install it, try again and let me know if you have any issue.
