### ISSUE TITLE
Unable to open .wav files saved in r with Raven

### ISSUE THREAD

**Issue by CTO22** [maRce10/Rraven#2]
I'm looking for advice on saving wave files so they are viewable in Raven following manipulation in R.

I have code that opens a portion of a long .wav file (based on a specific/referred selection), then saves just that portion of the wave file.  I have tried seewav and tuneR,  The full input file and the clipped file look the same: 
Wave Object - R object before saving
	Number of Samples:      73200
	Duration (seconds):     3.05
	Samplingrate (Hertz):   24000
	Channels (Mono/Stereo): Stereo
	PCM (integer format):   TRUE
	Bit (8/16/24/32/64):    16 

But when I reopen the saved file it appears one channel has been dropped when saving.  

Wave Object - reopened R object after saving
	Number of Samples:      73200
	Duration (seconds):     3.05
	Samplingrate (Hertz):   24000
	Channels (Mono/Stereo): Mono
	PCM (integer format):   TRUE
	Bit (8/16/24/32/64):    16 
all of the saved files can be played using audio programs (e.g. windows media player, but none can be opened with Raven Pro 1.15.

Do you have any advice?

**Comment by maRce10** [comment]
Hi 

can you send me the code (ideally a reproducible example using seewaves or warbleR example wave objects)

thanks

**Comment by CTO22** [comment]
Hi Marcelo,


My apologies for the delay.  I found out my problem.  I was not specifying "extensible = F" within the writeWave command.  The folks at Cornell Labs said the new update might resolve that issue.


Many thanks

Cory


________________________________
