### ISSUE TITLE
Default text file name temp.bcv.txt is not compatible with parallelization

### ISSUE THREAD

**Issue by DanWoodrich** [maRce10/Rraven#5]
Hi Marcelo, 

It appears that the generated temp.bcv.txt file does not work with parallelization, which surprisingly (and to my delight) works great otherwise. Raven does not seem to use CPU cores very efficiently on the detectors so it is a big performance boost to use parallelization. My parallelization structure I am using, which apparently has good compatibility with the Raven API is foreach. 

Adding a unique variable to the name of the 'temp.bcv.txt' makes parallelization run smoothly- I run a series of detectors in my script so I just chose the detector name variable for my script. The reason why I didn't make a branch is because I imagine there is better practice on how to guarantee a unique name for a wider variety of use cases, which I'll leave up to you if you are interested in implementing this functionality. 

Cheers, 
Dan

**Comment by maRce10** [comment]
Hi Daniel

thanks for the heads-up. So if I understand correctly, your suggestion is to save the temporal file with a unique name each time so it is not overwritten by different processes when the function is parallelized, right?

**Comment by DanWoodrich** [comment]
Yes, that is correct. Sure thing.

**Comment by maRce10** [comment]
I followed your suggestion so now raven_batch_detec() creates a unique name for each temporal file. I also added the option to run in parallel (new parallel argument), which works fine in linux (but might not work in windows). The updated function is now on github

thanks!

**Comment by DanWoodrich** [comment]
Very cool. Thanks Marcelo!
