### ISSUE TITLE
Problems with empty selection tables

### ISSUE THREAD

**Issue by fabiola-chirino** [maRce10/Rraven#7]
Hi maRce10! 

I'm having problems with the function imp_raven. It turns out that when I try to import my selection tables from Raven to R, if I have an empty selection table, my code doesn't work. And I also don't know if I can delete that selection table directly from R, because I have too many selection tables that I want to analyze with  your super awesome warbleR package !!! 

Thanks !

**Comment by robinsandfort** [comment]
Same problem over here: If there are any empty selection files this error with the imp_raven()
function kicks in:
Error in data.frame(sl.list[[x]], selec.file = names(sl.list)[x], check.names = FALSE) : 
arguments imply differing number of rows: 0, 1

**Comment by maRce10** [comment]
I think this is fixed in the developmental version. Can you install Rraven from github and try again?

`remotes::install_github("maRce10/Rraven")`

**Comment by robinsandfort** [comment]
Hi Marcelo,
thanks a lot! This fixed my issue.
